### ISSUE TITLE
Windows 10 user account username is used instead of .env username or USERNAME value

### ISSUE THREAD

**Issue by silentchaostheory** [morficus/cypress-dotenv#25]
In Windows 10, when I install versions above 1.2.2 of this plugin, my user account username is used instead of the .env file USERNAME or username value.

I updated dotenv after realizing I was using a version that was considered incompatible and still saw the issue. This probably means the user executing the npm run command in Powershell, os.userInfo().username, is being used instead of the .env file username|USERNAME.

- Edition: Windows 10 Pro
- Version: 20H2
- Installed on: ‎1/‎18/‎2021
- OS build: 19042.1288
- Experience: Windows Feature Experience Pack 120.2212.3920.0

.env file variables that caused issues and how they appear in Cypress configuration.
![cypressIssue_LI](https://user-images.githubusercontent.com/56895341/137168184-91cb6a2a-416e-4fd1-955b-e1e2dc43cae6.jpg)

**Comment by morficus** [comment]
hey @silentchaostheory -- I know it has been 3 years since you opened this issue, but one possible workaround would be to prefix what's in your `.env` file with `CYPRESS_`. so in our case that would be `CYPRESS_username`.

I think the root issue is that there is an env var name collision.

I'm going to close this issue for now, but please feel free to reopen it if you're still having a problem
